create table if not exists late_requests (

    id bigint generated by default as identity primary key,

    telegram_id bigint not null,

    username text,

    name text not null,

    message text,

    status text default 'new',

    created_at timestamp with time zone default now()

);
