-- Таблица заявок об опоздании

create table if not exists late_requests (
    id bigint generated by default as identity primary key,

    telegram_id bigint not null,

    username text,

    name text not null,

    message text,

    status text default 'new',

    created_at timestamp with time zone default now()
);


-- Индекс для быстрого поиска по Telegram ID

create index if not exists late_requests_telegram_id_idx
on late_requests(telegram_id);


-- Разрешаем доступ через API Supabase

alter table late_requests enable row level security;


create policy "Allow insert late requests"
on late_requests
for insert
to anon
with check (true);


create policy "Allow read late requests"
on late_requests
for select
to anon
using (true);
